# Generated by Django 4.2.26 on 2025-11-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(verbose_name='Исходный текст')),
                ('normalized_text', models.TextField(blank=True, verbose_name='Нормализованный текст')),
                ('parsed_data', models.JSONField(blank=True, null=True, verbose_name='Распарсенные данные')),
                ('status', models.CharField(max_length=32, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип ссылки',
                'verbose_name_plural': 'Типы ссылок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=255, verbose_name='Имя поля')),
                ('severity', models.CharField(max_length=16, verbose_name='Серьезность')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='app.reference', verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Проблема ссылки',
                'verbose_name_plural': 'Проблемы ссылок',
                'ordering': ['reference', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя поля')),
                ('label', models.CharField(max_length=255, verbose_name='Метка')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядок')),
                ('separator_before', models.CharField(blank=True, max_length=64, verbose_name='Разделитель перед')),
                ('separator_after', models.CharField(blank=True, max_length=64, verbose_name='Разделитель после')),
                ('pattern', models.TextField(verbose_name='Шаблон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('reference_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app.referencetype', verbose_name='Тип ссылки')),
            ],
            options={
                'verbose_name': 'Поле ссылки',
                'verbose_name_plural': 'Поля ссылок',
                'ordering': ['reference_type', 'order_index'],
            },
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='app.referencetype', verbose_name='Тип ссылки'),
        ),
    ]
